name: Build
on: 
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run ktlint check (codestyle)
        uses: ./gradlew ktlintcheck
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Detekt check (codestyle)
        uses: ./gradlew detekt
